### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/wunderlist#1]
Let me know when you're done, then I'll do a quick code review.

**Comment by mpociot** [comment]
Do your magic, Freek

**Comment by freekmurze** [comment]
On it! 😄

**Comment by freekmurze** [comment]
Like expected, your code was already excellent. I only needed to change some minor things.

In the tests I changed the recurrence tests to make use of a [dataProvider](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers). That makes it clear the those tests were always testing the same thing.

**Comment by mpociot** [comment]
Thank you.

Yes, using the dataProvider is a much better (and cleaner) choice. 👍
