### ISSUE TITLE
Quick query

### ISSUE THREAD

**Issue by JayBizzle** [laravel-notification-channels/wunderlist#8]
Just quick query.

Wondering under what circumstances [this would return early](https://github.com/laravel-notification-channels/wunderlist/blob/master/src/WunderlistChannel.php#L37)?

Thanks

**Comment by mpociot** [comment]
Oh you're right. Since collect always returns a collection, this will never fail.
Are you open to send a PR?

**Comment by JayBizzle** [comment]
Yes, can do a PR no problem.

I used this repo as a basis of my ionic-push-notifications channel and noticed my test coverage was 99% because of this line and couldn't figure out when it would get executed.

Should we just remove the conditional, or is there something we should be checking for?

**Comment by mpociot** [comment]
In this case we should check that the routing collection has a list_id and a access token, in order to send the notification

**Comment by JayBizzle** [comment]
Done, see #9
